# Generated by Django 3.2.4 on 2021-12-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('company_website', models.URLField(verbose_name='Company Website')),
                ('company_job_postings', models.URLField(verbose_name='Company Website Job Posting Site')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(max_length=50, verbose_name='Current Status')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_posting_url', models.URLField(verbose_name='Job Posting URL')),
                ('job_description', models.TextField(verbose_name='Job Description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.currentstatus')),
            ],
        ),
        migrations.CreateModel(
            name='PreInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_found_date', models.DateField(verbose_name='Job Found Date')),
                ('apply', models.BooleanField(verbose_name='Have Applied?')),
                ('date_applied', models.DateField(blank=True, null=True, verbose_name='Applied Date')),
                ('follow_up_email', models.BooleanField(verbose_name='Have Followed Up Email?')),
                ('follow_up_email_date', models.DateField(blank=True, null=True, verbose_name='Follow Up Email Date')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('additional_informaiton', models.TextField(verbose_name='Additional Person Information')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_interview', models.DateField(verbose_name='Date of Interview')),
                ('send_thank_you', models.BooleanField(verbose_name='Sent Thank You?')),
                ('date_thank_you_sent', models.DateField(blank=True, null=True, verbose_name='Date Thank You Sent')),
                ('follow_up_email', models.BooleanField(verbose_name='Sent Follow Up Email?')),
                ('follow_up_email_date', models.DateField(blank=True, null=True, verbose_name='Date Follow Up Email Sent')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.person')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposting')),
            ],
        ),
    ]
