# Generated by Django 3.2.4 on 2021-12-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_additional_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='additional_informaiton',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Person Information'),
        ),
    ]
